swagger: "2.0"
info:
  description: From the todo list tutorial on goswagger.io
  title: A Todo list application
  version: 1.0.0

schemes:
- http
host : 127.0.0.1:10000
paths:
  /profiles:
    get:
      tags:
        - GET Request
      parameters:
        - name: name
          in: query
          type: string
          
          
  
      responses:
        200:
          description: list the todo operations
          schema:
            
            items:
              $ref: "#/definitions/profiles"

definitions:
  profiles:
  
    required:
      - "name"
    properties:
      name:
        type: string
        format: int64
        readOnly: false
